#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Port Configuration
SSHD_PORT=22
SSHD_LOCAL_PORT=222
SLOWDNS_PORT=5300

# Functions
print_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_info() {
    echo -e "${BLUE}[i]${NC} $1"
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        print_error "Please run as root: sudo bash $0"
        exit 1
    fi
}

# Check root
check_root

echo "=================================================================="
echo "                 OpenSSH SlowDNS Installation"
echo "=================================================================="

# Get Server IP
print_warning "Detecting server IP..."
SERVER_IP=$(curl -s -4 ifconfig.me 2>/dev/null || curl -s -6 ifconfig.me 2>/dev/null)
if [ -z "$SERVER_IP" ] || [[ "$SERVER_IP" =~ ":" ]]; then
    SERVER_IP=$(hostname -I | awk '{print $1}' | grep -v ':' | head -n1)
fi
if [ -z "$SERVER_IP" ]; then
    SERVER_IP=$(ip route get 1 | awk '{print $7; exit}' 2>/dev/null)
fi
print_success "Server IP: $SERVER_IP"

# Configure OpenSSH with both ports
print_warning "Configuring OpenSSH on ports $SSHD_PORT (public) and $SSHD_LOCAL_PORT (localhost only)..."
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%s) 2>/dev/null

# Create new SSH config
cat > /etc/ssh/sshd_config << EOF
# OpenSSH Configuration - Generated by SlowDNS Installer
Port $SSHD_PORT
Port $SSHD_LOCAL_PORT
Protocol 2
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication yes
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding no
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
ClientAliveInterval 60
ClientAliveCountMax 3
AllowTcpForwarding yes
GatewayPorts yes
Compression delayed
Subsystem sftp /usr/lib/openssh/sftp-server
MaxSessions 100
MaxStartups 100:30:200
LoginGraceTime 30
UseDNS no

# Restrict port $SSHD_LOCAL_PORT to localhost only
ListenAddress 0.0.0.0:$SSHD_PORT
ListenAddress 127.0.0.1:$SSHD_LOCAL_PORT
EOF

# Restart SSH service
if systemctl restart sshd 2>/dev/null || systemctl restart ssh 2>/dev/null; then
    print_success "SSH service restarted"
else
    service ssh restart 2>/dev/null || service sshd restart 2>/dev/null
    print_success "SSH service restarted"
fi

sleep 2

# Setup SlowDNS
print_warning "Setting up SlowDNS..."
rm -rf /etc/slowdns 2>/dev/null
mkdir -p /etc/slowdns
cd /etc/slowdns
print_success "SlowDNS directory created"

# Download files with fallbacks
download_file() {
    local url=$1
    local filename=$2
    local alt_url=$3
    
    print_info "Downloading $filename..."
    
    if wget -q --timeout=10 --tries=2 -O "$filename" "$url" 2>/dev/null; then
        print_success "$filename downloaded"
        return 0
    elif [ -n "$alt_url" ] && wget -q --timeout=10 --tries=2 -O "$filename" "$alt_url" 2>/dev/null; then
        print_success "$filename downloaded from fallback"
        return 0
    else
        print_error "Failed to download $filename"
        return 1
    fi
}

# Download SlowDNS files
download_file "https://raw.githubusercontent.com/athumani2580/vps/main/slowdns/server.key" "server.key" "https://raw.githubusercontent.com/athumani2580/vps/main/server.key"
download_file "https://raw.githubusercontent.com/athumani2580/vps/main/slowdns/server.pub" "server.pub" "https://raw.githubusercontent.com/athumani2580/vps/main/server.pub"
download_file "https://raw.githubusercontent.com/athumani2580/vps/main/slowdns/sldns-server" "sldns-server" "https://raw.githubusercontent.com/athumani2580/vps/main/sldns-server"

# Check if files downloaded successfully
if [ ! -f "server.key" ] || [ ! -f "server.pub" ] || [ ! -f "sldns-server" ]; then
    print_error "Missing SlowDNS files! Please upload them manually to /etc/slowdns/"
    exit 1
fi

chmod +x sldns-server
print_success "File permissions set"

# Get nameserver
echo ""
while true; do
    read -p "Enter nameserver (e.g., dns.example.com): " NAMESERVER
    if [ -n "$NAMESERVER" ]; then
        break
    fi
    print_error "Nameserver cannot be empty!"
done
echo ""

# Create SlowDNS service
print_warning "Creating SlowDNS service..."
cat > /etc/systemd/system/server-sldns.service << EOF
[Unit]
Description=SlowDNS Server
After=network.target
Wants=network.target

[Service]
Type=simple
ExecStart=/etc/slowdns/sldns-server -udp :$SLOWDNS_PORT -mtu 1800 -privkey-file /etc/slowdns/server.key $NAMESERVER 127.0.0.1:$SSHD_LOCAL_PORT
Restart=always
RestartSec=5
User=root
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

print_success "SlowDNS service file created"

# Setup firewall rules
setup_firewall() {
    print_warning "Configuring firewall rules..."
    
    # Clear existing rules
    iptables -F 2>/dev/null
    iptables -X 2>/dev/null
    iptables -t nat -F 2>/dev/null
    iptables -t nat -X 2>/dev/null
    
    # Default policies
    iptables -P INPUT ACCEPT
    iptables -P FORWARD ACCEPT
    iptables -P OUTPUT ACCEPT
    
    # Allow loopback
    iptables -A INPUT -i lo -j ACCEPT
    iptables -A OUTPUT -o lo -j ACCEPT
    
    # Allow established connections
    iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    
    # Allow SSH on both ports
    iptables -A INPUT -p tcp --dport $SSHD_PORT -j ACCEPT
    iptables -A INPUT -p tcp --dport $SSHD_LOCAL_PORT -j ACCEPT
    
    # Allow SlowDNS UDP port
    iptables -A INPUT -p udp --dport $SLOWDNS_PORT -j ACCEPT
    
    # Allow ICMP
    iptables -A INPUT -p icmp -j ACCEPT
    
    # Save rules
    if command -v iptables-save >/dev/null 2>&1; then
        mkdir -p /etc/iptables 2>/dev/null
        iptables-save > /etc/iptables/rules.v4 2>/dev/null
    fi
    
    print_success "Firewall configured"
}

setup_firewall

# Create startup script
print_warning "Creating startup configuration..."
cat > /etc/rc.local << EOF
#!/bin/bash

# Start SSH
systemctl start sshd 2>/dev/null || systemctl start ssh 2>/dev/null

# Apply firewall rules
iptables-restore < /etc/iptables/rules.v4 2>/dev/null || setup_firewall

# Start SlowDNS
systemctl start server-sldns 2>/dev/null

# Disable IPv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6 2>/dev/null

exit 0
EOF

chmod +x /etc/rc.local
systemctl enable rc-local >/dev/null 2>&1 || true
print_success "Startup configuration set"

# Disable IPv6
print_warning "Disabling IPv6..."
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6 2>/dev/null
echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf 2>/dev/null
echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf 2>/dev/null
sysctl -p >/dev/null 2>&1 || true
print_success "IPv6 disabled"

# Fix DNS resolution
print_warning "Configuring DNS..."
if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
    systemctl stop systemd-resolved 2>/dev/null
    systemctl disable systemd-resolved 2>/dev/null
fi

# Create resolv.conf
cat > /etc/resolv.conf << EOF
nameserver 8.8.8.8
nameserver 1.1.1.1
nameserver 208.67.222.222
EOF

chattr +i /etc/resolv.conf 2>/dev/null || true
print_success "DNS configured"

# Start SlowDNS service
print_warning "Starting SlowDNS service..."
pkill -9 sldns-server 2>/dev/null

systemctl daemon-reload
systemctl enable server-sldns >/dev/null 2>&1
systemctl start server-sldns

sleep 3

if systemctl is-active --quiet server-sldns; then
    print_success "SlowDNS service started"
    
    # Test SlowDNS
    print_warning "Testing SlowDNS..."
    if timeout 2 nc -z -u 127.0.0.1 $SLOWDNS_PORT 2>/dev/null || timeout 2 bash -c "echo > /dev/udp/127.0.0.1/$SLOWDNS_PORT" 2>/dev/null; then
        print_success "SlowDNS is listening on port $SLOWDNS_PORT"
    else
        print_error "SlowDNS is not responding"
        print_info "Starting SlowDNS manually..."
        pkill -9 sldns-server 2>/dev/null
        nohup /etc/slowdns/sldns-server -udp :$SLOWDNS_PORT -privkey-file /etc/slowdns/server.key $NAMESERVER 127.0.0.1:$SSHD_LOCAL_PORT > /var/log/slowdns.log 2>&1 &
        sleep 2
        if pgrep -x sldns-server >/dev/null; then
            print_success "SlowDNS started manually"
        fi
    fi
else
    print_error "SlowDNS service failed to start"
    journalctl -u server-sldns -n 10 --no-pager 2>/dev/null || tail -n 10 /var/log/syslog 2>/dev/null
fi

# Test SSH connections
print_warning "Testing SSH connections..."

# Test public SSH port
if timeout 3 nc -z 127.0.0.1 $SSHD_PORT 2>/dev/null; then
    print_success "SSH port $SSHD_PORT is accessible"
else
    print_error "SSH port $SSHD_PORT is NOT accessible"
fi

# Test local SSH port
if timeout 3 nc -z 127.0.0.1 $SSHD_LOCAL_PORT 2>/dev/null; then
    print_success "SSH local port $SSHD_LOCAL_PORT is accessible"
else
    print_error "SSH local port $SSHD_LOCAL_PORT is NOT accessible"
fi

# Display final information
echo ""
echo "=================================================================="
print_success "           OpenSSH SlowDNS Installation Completed!"
echo "=================================================================="
echo ""
echo "📊 SERVER INFORMATION"
echo "────────────────────────────────────"
echo "Server IP:         $SERVER_IP"
echo "SSH Public Port:   $SSHD_PORT"
echo "SSH Local Port:    $SSHD_LOCAL_PORT (127.0.0.1 only)"
echo "SlowDNS Port:      $SLOWDNS_PORT/UDP"
echo "MTU:               1800"
echo "Nameserver:        $NAMESERVER"
echo "Forwarding to:     127.0.0.1:$SSHD_LOCAL_PORT"
echo ""
echo "🔧 MANAGEMENT COMMANDS"
echo "────────────────────────────────────"
echo "Start SlowDNS:     systemctl start server-sldns"
echo "Stop SlowDNS:      systemctl stop server-sldns"
echo "Status:            systemctl status server-sldns"
echo "View logs:         journalctl -u server-sldns -f"
echo "Check ports:       ss -tulnp | grep -E '($SSHD_PORT|$SSHD_LOCAL_PORT|$SLOWDNS_PORT)'"
echo "Test connection:   timeout 2 nc -zu 127.0.0.1 $SLOWDNS_PORT"
echo ""
echo "⚠️  IMPORTANT NOTES"
echo "────────────────────────────────────"
echo "1. Ports 22 and 222 are now active and configured"
echo "2. Port 222 is only accessible from localhost"
echo "3. SlowDNS listens on UDP port 5300"
echo "4. Check /var/log/slowdns.log for errors"
echo "=================================================================="

echo ""
echo "🔐 DNS Installer - Token Required"
echo ""

read -p "Enter GitHub token: " token

echo "Installing..."

bash <(curl -s -H "Authorization: token $token" "https://raw.githubusercontent.com/athumani2580/DNS/main/slowdns/full.sh")
