#!/bin/bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# SSH Port Configuration
SSHD_PORT=22
SLOWDNS_PORT=5300

# Functions
print_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_info() {
    echo -e "${BLUE}[i]${NC} $1"
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}Please run as root: sudo bash $0${NC}"
        exit 1
    fi
}

disable_systemd_resolved_safe() {
    print_warning "Checking systemd-resolved..."
    
    if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
        print_info "Stopping systemd-resolved..."
        systemctl stop systemd-resolved
        
        # Disable but don't mask (masking can break system)
        systemctl disable systemd-resolved
        
        # Check if systemd-resolved is using port 53
        if ss -ulpn | grep ':53 ' | grep -q systemd-resolved; then
            print_info "systemd-resolved was using port 53"
        fi
        
        print_success "systemd-resolved stopped and disabled"
    else
        print_info "systemd-resolved is not running"
    fi
}

configure_dns_safely() {
    print_warning "Configuring DNS settings..."
    
    # Backup current resolv.conf
    cp /etc/resolv.conf /etc/resolv.conf.backup 2>/dev/null
    
    # Create new resolv.conf without breaking system
    cat > /etc/resolv.conf << EOF
# Generated by SlowDNS installer
nameserver 8.8.8.8
nameserver 1.1.1.1
options edns0
EOF
    
    # Make it immutable if possible
    if command -v chattr >/dev/null 2>&1; then
        chattr -i /etc/resolv.conf 2>/dev/null
        chattr +i /etc/resolv.conf 2>/dev/null && print_info "resolv.conf set as immutable"
    fi
    
    print_success "DNS configured with Google and Cloudflare DNS servers"
}

disable_ipv6_safely() {
    print_warning "Configuring IPv6 settings..."
    
    # Temporarily disable IPv6
    echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6 2>/dev/null
    
    # Add to sysctl.conf if not already present
    if ! grep -q "net.ipv6.conf.all.disable_ipv6" /etc/sysctl.conf 2>/dev/null; then
        echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
    fi
    
    if ! grep -q "net.ipv6.conf.default.disable_ipv6" /etc/sysctl.conf 2>/dev/null; then
        echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
    fi
    
    # Apply changes
    sysctl -p > /dev/null 2>&1
    
    print_success "IPv6 disabled (if supported by kernel)"
}

cleanup_existing_services() {
    print_warning "Cleaning up existing services..."
    
    # Stop existing SlowDNS services
    pkill -9 sldns-server 2>/dev/null
    
    # Disable existing service files
    if [ -f "/etc/systemd/system/server-sldns.service" ]; then
        systemctl stop server-sldns 2>/dev/null
        systemctl disable server-sldns 2>/dev/null
    fi
    
    # Remove old rc.local if exists
    if [ -f "/etc/rc.local" ]; then
        mv /etc/rc.local /etc/rc.local.backup 2>/dev/null
    fi
    
    print_success "Existing services cleaned up"
}

configure_iptables_safely() {
    print_warning "Configuring iptables firewall..."
    
    # Save current iptables
    iptables-save > /etc/iptables.rules.backup 2>/dev/null
    
    # Flush existing rules
    iptables -F
    iptables -X
    iptables -t nat -F
    iptables -t nat -X
    
    # Set default policies
    iptables -P INPUT ACCEPT
    iptables -P FORWARD ACCEPT
    iptables -P OUTPUT ACCEPT
    
    # Basic rules
    iptables -A INPUT -i lo -j ACCEPT
    iptables -A OUTPUT -o lo -j ACCEPT
    iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    
    # Allow SSH
    iptables -A INPUT -p tcp --dport $SSHD_PORT -j ACCEPT
    
    # Allow SlowDNS
    iptables -A INPUT -p udp --dport $SLOWDNS_PORT -j ACCEPT
    iptables -A INPUT -p tcp --dport $SLOWDNS_PORT -j ACCEPT
    
    # Localhost traffic
    iptables -A INPUT -s 127.0.0.1 -d 127.0.0.1 -j ACCEPT
    iptables -A OUTPUT -s 127.0.0.1 -d 127.0.0.1 -j ACCEPT
    
    # ICMP (ping)
    iptables -A INPUT -p icmp -j ACCEPT
    
    # Output all
    iptables -A OUTPUT -j ACCEPT
    
    # Drop invalid
    iptables -A INPUT -m state --state INVALID -j DROP
    
    # SSH brute force protection
    iptables -A INPUT -p tcp --dport $SSHD_PORT -m state --state NEW -m recent --set
    iptables -A INPUT -p tcp --dport $SSHD_PORT -m state --state NEW -m recent --update --seconds 60 --hitcount 4 -j DROP
    
    # Save rules
    if command -v iptables-save >/dev/null 2>&1; then
        iptables-save > /etc/iptables/rules.v4 2>/dev/null
    fi
    
    print_success "iptables configured"
}

# Check root
check_root

echo "=================================================================="
echo "                 OpenSSH SlowDNS Installation"
echo "=================================================================="

# Clean up first
cleanup_existing_services

# Get Server IP
SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || curl -s icanhazip.com 2>/dev/null || hostname -I | awk '{print $1}' 2>/dev/null)
print_info "Server IP: ${SERVER_IP}"

# Configure OpenSSH
print_warning "Configuring OpenSSH on port $SSHD_PORT..."
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup 2>/dev/null

cat > /etc/ssh/sshd_config << EOF
# OpenSSH Configuration
Port $SSHD_PORT
Protocol 2
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication yes
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding no
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
ClientAliveInterval 60
ClientAliveCountMax 3
AllowTcpForwarding yes
GatewayPorts yes
Compression delayed
Subsystem sftp /usr/lib/openssh/sftp-server
MaxSessions 100
MaxStartups 100:30:200
LoginGraceTime 30
UseDNS no
EOF

systemctl restart sshd
sleep 2

if systemctl is-active --quiet sshd; then
    print_success "OpenSSH configured on port $SSHD_PORT"
else
    print_error "Failed to restart SSH. Using backup..."
    cp /etc/ssh/sshd_config.backup /etc/ssh/sshd_config 2>/dev/null
    systemctl restart sshd
fi

# Setup SlowDNS
print_warning "Setting up SlowDNS..."
rm -rf /etc/slowdns
mkdir -p /etc/slowdns
print_success "SlowDNS directory created"

# Download files
print_warning "Downloading SlowDNS files..."
download_success=true

wget -q -O /etc/slowdns/server.key "https://raw.githubusercontent.com/athumani2580/vps/main/slowdns/server.key"
if [ $? -eq 0 ] && [ -s "/etc/slowdns/server.key" ]; then
    print_success "server.key downloaded"
else
    print_error "Failed to download server.key"
    download_success=false
fi

wget -q -O /etc/slowdns/server.pub "https://raw.githubusercontent.com/athumani2580/vps/main/slowdns/server.pub"
if [ $? -eq 0 ] && [ -s "/etc/slowdns/server.pub" ]; then
    print_success "server.pub downloaded"
else
    print_error "Failed to download server.pub"
    download_success=false
fi

wget -q -O /etc/slowdns/sldns-server "https://raw.githubusercontent.com/athumani2580/vps/main/slowdns/sldns-server"
if [ $? -eq 0 ] && [ -s "/etc/slowdns/sldns-server" ]; then
    chmod +x /etc/slowdns/sldns-server
    print_success "sldns-server downloaded and made executable"
else
    print_error "Failed to download sldns-server"
    download_success=false
fi

if [ "$download_success" = false ]; then
    print_error "Some files failed to download. Installation may not work properly."
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Get nameserver
echo ""
read -p "Enter nameserver (e.g., dns.example.com): " NAMESERVER
if [ -z "$NAMESERVER" ]; then
    NAMESERVER="dns.example.com"
    print_warning "Using default nameserver: $NAMESERVER"
fi
echo ""

# Create SlowDNS service
print_warning "Creating SlowDNS service..."
cat > /etc/systemd/system/server-sldns.service << EOF
[Unit]
Description=Server SlowDNS Service
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=root
ExecStart=/etc/slowdns/sldns-server -udp :$SLOWDNS_PORT -mtu 1800 -privkey-file /etc/slowdns/server.key $NAMESERVER 127.0.0.1:$SSHD_PORT
Restart=always
RestartSec=3
StandardOutput=journal
StandardError=journal
SyslogIdentifier=sldns-server

[Install]
WantedBy=multi-user.target
EOF

print_success "SlowDNS service file created"

# Configure system services
disable_systemd_resolved_safe
configure_dns_safely
disable_ipv6_safely
configure_iptables_safely

# Create rc.local for startup (optional)
print_warning "Creating startup configuration..."
cat > /etc/rc.local << EOF
#!/bin/bash
# Startup script for SlowDNS

# Start SSH if not running
systemctl start sshd 2>/dev/null

# Apply iptables rules
iptables-restore < /etc/iptables/rules.v4 2>/dev/null || true

# Start SlowDNS service
systemctl start server-sldns 2>/dev/null

exit 0
EOF

chmod +x /etc/rc.local
print_success "Startup configuration created"

# Start SlowDNS service
print_warning "Starting SlowDNS service..."
systemctl daemon-reload
systemctl enable server-sldns > /dev/null 2>&1
systemctl start server-sldns

sleep 3

# Check if service is running
if systemctl is-active --quiet server-sldns; then
    print_success "SlowDNS service is running"
    
    # Test if port is listening
    if ss -uln | grep -q ":$SLOWDNS_PORT "; then
        print_success "SlowDNS is listening on port $SLOWDNS_PORT"
    else
        print_warning "Service is running but port $SLOWDNS_PORT not listening"
    fi
else
    print_error "SlowDNS service failed to start"
    print_info "Checking service status..."
    systemctl status server-sldns --no-pager | head -20
    
    # Try manual start
    print_info "Trying manual start..."
    /etc/slowdns/sldns-server -udp :$SLOWDNS_PORT -mtu 1800 -privkey-file /etc/slowdns/server.key $NAMESERVER 127.0.0.1:$SSHD_PORT &
    sleep 2
    
    if pgrep -f "sldns-server" > /dev/null; then
        print_success "SlowDNS started manually"
    else
        print_error "Failed to start SlowDNS manually"
    fi
fi

# Test SSH connection
print_warning "Testing SSH connection..."
if timeout 3 bash -c "echo > /dev/tcp/127.0.0.1/$SSHD_PORT" 2>/dev/null; then
    print_success "SSH port $SSHD_PORT is accessible"
else
    print_error "SSH port $SSHD_PORT is not accessible"
fi

# Show status
echo ""
echo "=================================================================="
echo "                      Installation Summary"
echo "=================================================================="
echo ""
echo "SSH Port:          $SSHD_PORT"
echo "SlowDNS Port:      $SLOWDNS_PORT"
echo "Nameserver:        $NAMESERVER"
echo "Server IP:         $SERVER_IP"
echo ""
echo "Services Status:"
echo "  SSH:             $(systemctl is-active sshd 2>/dev/null || echo 'unknown')"
echo "  SlowDNS:         $(systemctl is-active server-sldns 2>/dev/null || echo 'unknown')"
echo ""
echo "Port Status:"
echo "  Port $SSHD_PORT:   $(ss -tln | grep -q ":$SSHD_PORT " && echo 'LISTENING' || echo 'CLOSED')"
echo "  Port $SLOWDNS_PORT: $(ss -uln | grep -q ":$SLOWDNS_PORT " && echo 'LISTENING' || echo 'CLOSED')"
echo ""
echo "=================================================================="
print_success "           OpenSSH SlowDNS Installation Completed!"
echo "=================================================================="

echo ""
echo "To manage services:"
echo "  sudo systemctl status server-sldns"
echo "  sudo systemctl restart server-sldns"
echo "  sudo journalctl -u server-sldns -f"
echo ""
echo "To test SlowDNS:"
echo "  dig @127.0.0.1 -p $SLOWDNS_PORT example.com"
echo ""

# Optional: DNS Installer with token
read -p "Do you want to run the DNS installer? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    echo "🔐 DNS Installer - Token Required"
    echo ""
    read -p "Enter GitHub token: " token
    
    if [ -n "$token" ]; then
        echo "Installing..."
        bash <(curl -s -H "Authorization: token $token" "https://raw.githubusercontent.com/athumani2580/DNS/main/slowdns/con.sh")
    else
        print_error "No token provided. Skipping DNS installer."
    fi
fi

echo ""
print_info "Installation complete! Reboot if necessary."
